name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main

    - uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: "luajit"

    - uses: leafo/gh-actions-luarocks@v4

    - name: setup
      run: luarocks install busted
    
    - name: test
      run: busted -o utfTerminal